import "./globals.css";
import { Rubik } from "next/font/google";
import Navbar from "@components/Navbar/Navbar";
import SideNav from "@components/SideNav/SideNav";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"
        />
      </head>
      <body className={`${rubik.className}`}>
        <Navbar />
        <SideNav />
        {children}
      </body>
    </html>
  );
}
